### ISSUE TITLE
NPE when cancelling an EGF activity execution

### ISSUE THREAD

**Issue by pdulth** [pdulth/egf1#118]
A NPE is obtained when user manually cancel an EGF activity execution.

The following error is provided:

eclipse.buildId=M20110210-1200
java.version=1.6.0_37
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=fr_FR
Framework arguments:  -product com.thalesgroup.mde.mdk.product
Command-line arguments:  -product com.thalesgroup.mde.mdk.product -data D:\MDK\Workspace-runtime-mdk -dev file:D:/MDK/Workspace/.metadata/.plugins/org.eclipse.pde.core/mdk/dev.properties -console -os win32 -ws win32 -arch x86 -consoleLog

Error
Thu Apr 11 17:33:23 CEST 2013
InvocationException

org.eclipse.core.runtime.OperationCanceledException
at org.eclipse.egf.task.internal.nature.TaskNatureJava.invoke(TaskNatureJava.java:65)
at org.eclipse.egf.producer.ftask.internal.invocation.TaskProductionInvocation.invoke(TaskProductionInvocation.java:53)
at org.eclipse.egf.producer.ftask.internal.manager.TaskManager.invoke(TaskManager.java:104)
at org.eclipse.egf.producer.fprod.internal.manager.ProductionPlanInvocationManager.invoke(ProductionPlanInvocationManager.java:111)
at org.eclipse.egf.producer.fprod.internal.manager.ProductionPlanManager.invoke(ProductionPlanManager.java:131)
at org.eclipse.egf.producer.internal.manager.FactoryComponentManager.invoke(FactoryComponentManager.java:133)
at org.eclipse.egf.producer.fprod.internal.manager.ProductionPlanInvocationManager.invoke(ProductionPlanInvocationManager.java:111)
at org.eclipse.egf.producer.fprod.internal.manager.ProductionPlanManager.invoke(ProductionPlanManager.java:131)
at org.eclipse.egf.producer.internal.manager.FactoryComponentManager.invoke(FactoryComponentManager.java:133)
at org.eclipse.egf.producer.fprod.internal.manager.ProductionPlanInvocationManager.invoke(ProductionPlanInvocationManager.java:111)
at org.eclipse.egf.producer.fprod.internal.manager.ProductionPlanManager.invoke(ProductionPlanManager.java:131)
at org.eclipse.egf.producer.internal.manager.FactoryComponentManager.invoke(FactoryComponentManager.java:133)
at org.eclipse.egf.producer.ui.internal.actions.RunActivityAction$1.runInWorkspace(RunActivityAction.java:219)
at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

`🆔 ECLIPSE-405485` `👷 idrissa.dieng` `📅 2013-04-11`

**Comment by pdulth** [comment]
**idrissa.dieng** commented on 2013-04-11
> To fix this problem I suggest adding in RunActivityAction#.new WorkspaceJob() {...}.runInWorkspace(IProgressMonitor) (Line 237) a catch clause for "OperationCanceledException" exception at first like this:
 > 
 > catch (OperationCanceledException ex) {
 >     return Status.CANCEL_STATUS;
 > }

**thomas.guiu** commented on 2013-04-12
> I guess the NPE is the InvocationException since I didn't get any NPE while replaying the usecase.
 > Your suggestion is good but we need to prevent the wrapping of the OperationCanceledException into an InvocationException.
 > 
 > The issue is fixed.
 > Thank you for your feedback.

**idrissa.dieng** commented on 2013-04-12
> Yep I agree.
 > 
 > Thanks!!!
 > 
 > (In reply to comment #2)
 > > I guess the NPE is the InvocationException since I didn't get any NPE while
 > > replaying the usecase.
 > > Your suggestion is good but we need to prevent the wrapping of the
 > > OperationCanceledException into an InvocationException.
 > > 
 > > The issue is fixed.
 > > Thank you for your feedback.
