### ISSUE TITLE
[EGF Portfolio Acceleo3] Can't run Acceleo3 task with a project as an output

### ISSUE THREAD

**Issue by pdulth** [pdulth/egf1#159]
When running an Acceleo3 task, it isn't possible to choose a project as an output.

The output path must have at least 2 segments to run the task. 
it should perform the generation directly on a project, with an output path containing 1 segment, as in Acceleo3 runtime configuration.

- Raised Exception : 

java.lang.IllegalArgumentException: Path must include project and resource name
at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2164)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:222)
	at org.eclipse.egf.portfolio.task.acceleo3.engine.Acceleo3ScriptEngine.executeAcceleo3Task(Acceleo3ScriptEngine.java:61)
	at org.eclipse.egf.portfolio.task.acceleo3.engine.Acceleo3TaskNature.invoke(Acceleo3TaskNature.java:49)

`🆔 ECLIPSE-441715` `👷 radouani.anass` `📅 2014-08-13` `🔎 1.0`

**Comment by pdulth** [comment]
**benoit.langlois** commented on 2014-08-20
> Hello Anass,
 > 
 > It's the vacation period and Boubekeur is off the office for almost four weeks.
 > When he is back, it will be unfortunately too late for the Luna/SR1 release.
 > A pre-release of Luna/SR2 will be available in the EGF/Luna build [1].
 > I hope it won't be too late for you.
 > 
 > Benoit
 > 
 > [1] https://hudson.eclipse.org/egf/job/buckminster-egf-luna/

**radouani.anass** commented on 2014-09-29
> Attachment: [org.eclipse.egf.portfolio.task.acceleo3.patch](https://raw.githubusercontent.com/wiki/eclipse/capella/attachments/247451.patch)
 > Allow using workspace projects as output folders
 > 
 > Instead of searching for the folder in the workspace, the output path is appended to the workspace location as follows :
 > 
 > IPath targetFolderIPath = ResourcesPlugin.getWorkspace().getRoot().getLocation().append(targetUri);
 > 
 > 
 > targetForlderIPath : the absolute output path.
 > targetUri : the user's output path.
 > 
 > Anass

**matthieu.helleboid** commented on 2015-03-02
> Fixed in EGF 1.2.1
