### ISSUE TITLE
"Reverse codegen" action fails

### ISSUE THREAD

**Issue by pdulth** [pdulth/egf1#178]
java.lang.IllegalStateException: Path for method 'header' is null
	at org.eclipse.egf.pattern.extension.BasePatternInitializer.getFile(BasePatternInitializer.java:106)
	at org.eclipse.egf.pattern.extension.BasePatternInitializer.initContent(BasePatternInitializer.java:46)
	at org.eclipse.egf.emf.pattern.codegen.CodegenFcoreUtil.createPatterns(CodegenFcoreUtil.java:269)
	at org.eclipse.egf.emf.pattern.codegen.CodegenFcoreUtil$CreateCommand.doExecute(CodegenFcoreUtil.java:107)
	at org.eclipse.emf.transaction.RecordingCommand.execute(RecordingCommand.java:135)
	at org.eclipse.emf.workspace.EMFCommandOperation.doExecute(EMFCommandOperation.java:119)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
	at org.eclipse.emf.workspace.impl.WorkspaceCommandStackImpl.doExecute(WorkspaceCommandStackImpl.java:208)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)

`🆔 ECLIPSE-491495` `👷 thomas.guiu` `📅 2016-04-12` `🔎 1.0`

**Comment by pdulth** [comment]
**ci-bot** commented on 2016-04-15
> Gerrit change https://git.eclipse.org/r/70480 was merged to [master].
 > Commit: http://git.eclipse.org/c/egf/org.eclipse.emf.egf.git/commit/?id=80b40ea6f55f2f5c130ba4a5d15878bdc88254a1

**thomas.guiu** commented on 2016-04-19
> fixed
