### ISSUE TITLE
Fix encoding while running a generation chain model

### ISSUE THREAD

**Issue by pdulth** [pdulth/egf1#192]
org.eclipse.egf.core.producer.InvocationException: Unable to find an associated Fcore with 'platform:/plugin/org.eclipse.egf.chain.my/model/My%20model.fcore'.
	at org.eclipse.egf.producer.internal.manager.ModelElementManager.<init>(ModelElementManager.java:143)
	at org.eclipse.egf.producer.internal.manager.ActivityManager.<init>(ActivityManager.java:39)
	at org.eclipse.egf.producer.internal.manager.FactoryComponentManager.<init>(FactoryComponentManager.java:45)
	at org.eclipse.egf.producer.manager.FactoryComponentManagerFactory.createProductionManager(FactoryComponentManagerFactory.java:31)
	at org.eclipse.egf.producer.internal.manager.FactoryComponentManagerProducer.doCreateActivityManager(FactoryComponentManagerProducer.java:38)
	at org.eclipse.egf.producer.internal.manager.FactoryComponentManagerProducer.doCreateActivityManager(FactoryComponentManagerProducer.java:1)
	at org.eclipse.egf.producer.manager.ActivityManagerProducer.createActivityManager(ActivityManagerProducer.java:47)
	at org.eclipse.egf.portfolio.genchain.tools.utils.RunActivityHelper.run(RunActivityHelper.java:44)
	at org.eclipse.egf.portfolio.genchain.tools.ui.actions.CreateFcoreHelper.runFcore(CreateFcoreHelper.java:207)
	at org.eclipse.egf.portfolio.genchain.tools.ui.actions.CreateFcoreHelper$1.runInWorkspace(CreateFcoreHelper.java:81)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

`🆔 ECLIPSE-512552` `👷 thomas.guiu` `📅 2017-02-22` `🔎 1.5.0`

**Comment by pdulth** [comment]
**ci-bot** commented on 2017-02-22
> Gerrit change https://git.eclipse.org/r/91601 was merged to [master].
 > Commit: http://git.eclipse.org/c/egf/org.eclipse.emf.egf.git/commit/?id=6c51d8fee060b1ba38909755f34c9acb4ea9239e

**thomas.guiu** commented on 2017-05-24
> done
